version: "3.3"

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME:?error}
      POSTGRES_PASSWORD: ${DB_PASSWORD?error}
    profiles:
      - dev
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?error}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?error}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    profiles:
      - dev

volumes:
  db_data:
    driver: local
